#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

UTS_MACHINE=$1
CC_VERSION="$2"
LD=$3

if test -z "$KBUILD_BUILD_USER"; then
	LINUX_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
else
	LINUX_COMPILE_BY=$KBUILD_BUILD_USER
fi
if test -z "$KBUILD_BUILD_HOST"; then
	LINUX_COMPILE_HOST=`uname -n`
else
	LINUX_COMPILE_HOST=$KBUILD_BUILD_HOST
fi

LD_VERSION=$(LC_ALL=C $LD -v | head -n1 |
		sed -e 's/(compatible with [^)]*)//' -e 's/[[:space:]]*$//')

cat <<EOF
#define UTS_MACHINE		"${UTS_MACHINE}"
#define LINUX_COMPILE_BY	"kleaf"
#define LINUX_COMPILE_HOST	"build-host"
#define LINUX_COMPILER		"Android (11368308, +pgo, +bolt, +lto, +mlgo, based on r510928) clang version 18.0.0 (https://android.googlesource.com/toolchain/llvm-project 477610d4d0d988e69dbc3fae4fe86bff3f07f2b5), LLD 18.0.0"
EOF
